###############################################################################
# docker-compose.runtime.yml  —  OpenHands production from GHCR
###############################################################################

services:
  openhands:
    image: ghcr.io/z360biz-llc/openhands:latest
    container_name: openhands-app-${DATE:-}
    restart: unless-stopped
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.all-hands.dev/all-hands-ai/runtime:0.48-nikolaik}
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace}
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands:/.openhands
      - ${WORKSPACE_BASE:-$PWD/workspace}:/opt/workspace_base
    stdin_open: true
    tty: true

volumes:
  openhands-workspace:
