###############################################################################
# docker-compose.yml  —  OpenHands UI with Daytona runtime (single service)
###############################################################################
version: "3.9"

services:
  openhands:
    # Use your pre-built app image from GHCR
    image: ghcr.io/z360biz-llc/openhands:latest
    container_name: openhands-app
    restart: unless-stopped

    environment:
      # Tell OpenHands to use Daytona instead of the local Docker runtime
      - OPENHANDS_RUNTIME_PROVIDER=daytona
      # Your personal / org Daytona API key (exported on the host or in .env)
      - DAYTONA_API_KEY=dtn_4a09e967aa21e26fc669c582bcb3c3de0a17329cfc8fef878f0d999263082c3d
      # Optional: where the agent will mount a working directory in Daytona
      - WORKSPACE_MOUNT_PATH=/opt/workspace_base

    ports:
      - "3000:3000"

    volumes:
      # Agent cache & config; **no /var/run/docker.sock needed**
      - ~/.openhands:/.openhands

networks:
  default:
    driver: bridge
