version: "3.9"

services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands:latest
    container_name: openhands-app
    restart: unless-stopped
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.48-nikolaik
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-/opt/workspace_base} # Safer default for container
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands:/.openhands
      - ./workspace:/opt/workspace_base
    depends_on:
      - openhands-runtime
    networks:
      - openhands

  openhands-runtime:
    image: docker.all-hands.dev/all-hands-ai/runtime:0.47-nikolaik
    command: ["python3", "-m", "openhands.runtime", "--listen", "0.0.0.0:30917"]
    container_name: openhands-runtime
    restart: unless-stopped
    ports:
      - "30917:30917"
      - "47017:47017"
      - "53309:53309"
      - "58691:58691"
    networks:
      - openhands

networks:
  openhands:
    driver: bridge
