version: "3.9"

services:
  openhands:
    image: ghcr.io/z360biz-llc/openhands:latest   # pulled from GitHub Container Registry
    container_name: openhands-app
    restart: unless-stopped
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - WORKSPACE_MOUNT_PATH=/opt/workspace_base
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands:/.openhands
      - ./workspace:/opt/workspace_base
    depends_on:
      - openhands-runtime
    networks:
      - openhands

  openhands-runtime:
    image: docker.all-hands.dev/all-hands-ai/runtime:0.48-nikolaik
    container_name: openhands-runtime
    restart: unless-stopped
    ports:
      - "30917:30917"
      - "47017:47017"
      - "53309:53309"
      - "58691:58691"
    networks:
      - openhands

networks:
  openhands:
    driver: bridge
